#!/bin/bash

# * open sa xdg bez argumenata
# * open sa argumentima
# * mozda kao preview text file-ova sa "cat"
# directory tree preview kao nixcasts
# directory (i ostalo, tipa xdg) 2 mogucnosti: pokazuje hidden fajlove i ne pokazuje




#fzf --height=30 --filepath-word --multi --cycle --preview="imv {}" | xargs -r xdg-open

#fd -t f -H -I | fzf -m --preview="xdg-mime query default {}" | xargs -ro -d "\n" xdg-open 2>&-

#fzf --height=30 --cycle --multi --preview='cat {}' +i --bind=ctrl-j:preview-half-page-down,ctrl-k:preview-half-page-up | xargs -ro -d "\n" xdg-open 2>&-
fzf --height=30 --cycle --multi --preview='cat {}' +i --bind=ctrl-j:preview-half-page-down,ctrl-k:preview-half-page-up | xargs xdg-open




#if [ -z "$1"]
#then
#    fd -t f -H -I | fzf --height=30 --filepath-word --multi --cycle | xargs -r xdg-open
#else
#    fd -t f -H -I | fzf --height=30 --filepath-word --multi --cycle | xargs -r $1
#fi

#konacni:
#sudo pacman -S $(pacman -Slq | fzf --height=30 --filepath-word --multi --cycle --preview="pacman -Si {}" --preview-window=:hidden --bind=space:toggle-preview)

exit 0
