#!/bin/bash

# This script checks if wlsunset is running, if it isn't, then it will start it. If it is already running, the script does nothing.

output1=$(ps aux | grep "wlsunset" | grep -v "grep wlsunset" ".scripts/run-wlsunset")

printf "output1=$output1"

if [ -z $output1 ]
then
    wlsunset -l 45 -L 20
fi

exit 0
